CREATE TABLE Puesto(
Puesto_ID NUMERIC(2,0) NOT NULL PRIMARY KEY,
Nivel CHAR(1) NOT NULL,
Clave VARCHAR(3) NOT NULL,
Sueldo NUMERIC(8,2) NOT NULL
);

CREATE TABLE Empleado(
EMPLEADO_ID VARCHAR(40) NOT NULL  PRIMARY KEY,
Nombre VARCHAR(40) NOT NULL,
Puesto_ID NUMERIC(2,0) NOT NULL
);

ALTER TABLE Empleado ADD CONSTRAINT Puesto_ID_FK FOREIGN KEY (Puesto_ID)
REFERENCES Puesto(Puesto_ID);
